### ISSUE TITLE
use curl instead of file_get_contents

### ISSUE THREAD

**Issue by cKlee** [lanthaler/JsonLD#67] opened 2015-11-13 10:23 UTC
Hi Markus,

I cannot use FileGetContentsLoader to retrieve external context documents because I'm behind a proxy. I asked a question on http://stackoverflow.com/questions/33687782/3rd-party-file-get-contents-behind-proxy if this problem can be solved with system settings. But even then, wouldn't it be better to use curl over file_get_contents? There seems to be a lot of trouble out there with file_get_contents and external documents.

Might be related to https://github.com/lanthaler/JsonLD/issues/4

**Comment by lanthaler** [comment] 2015-12-28 17:48
Yep, this is a duplicate of #4. I'm closing this issue in favour of the other one.

**Closed by lanthaler** 2015-12-28 17:48 UTC
